### ISSUE TITLE
Repository download link no longer valid

### ISSUE THREAD

**Issue by bstuart9** [juretta/stash-log-parser#1]
It looks like https://bitbucket.org/ssaasen/stash-log-parse is no longer valid link. 

`==> Downloading https://bitbucket.org/ssaasen/stash-log-parser/downloads/logparser-osx-x86_64-v3.1.tar.gz

curl: (22) The requested URL returned error: 404
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "stash-logparser"
Download failed: https://bitbucket.org/ssaasen/stash-log-parser/downloads/logparser-osx-x86_64-v3.1.tar.gz`

**Comment by juretta** [comment]
Sorry for the inconvenience. The repository has moved to https://bitbucket.org/atlassianlabs/stash-log-parser

Downloads there (https://bitbucket.org/atlassianlabs/stash-log-parser/downloads/) should work.
